title: Your Title
description: Your Description. version 1.2
author: username
permalink: /:title.html/
url: https://username.github.io
paginate: 7
paginate_path: "/page:num"
repo: username.github.io
owner: username

